"""updated tables to include more fish

Revision ID: 2d4ca69f7eaa
Revises: f6bf7267b4f7
Create Date: 2023-03-09 10:18:58.658519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4ca69f7eaa'
down_revision = 'f6bf7267b4f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
